# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JAXapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jcanalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
